#define MAX_ENTITIES_COUNT 1024
#define MAX_IMAGES_COUNT 1024
#define MAX_ITEMS_COUNT 1024

#define INV_COUNT 15
#define STACK_SIZE 100
#define INV_CELL_MARGIN 8
#define INV_CELL_SIZE 64
#define INV_UI_WIDTH 0.5
#define INV_UI_HEIGHT 0.5
#define INV_UI_INNER_MARGIN_X 0.15
#define INV_UI_INNER_MARGIN_Y 0.25
#define HOTBAR_AMOUNT 5